spring.application.name=url-shortner
spring.datasource.url=jdbc:mysql://localhost:3306/urlshortnerdb
spring.datasource.username=root
spring.datasource.password=Neeraj@0804
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true  this line is used if you want to see the sql queries in terminal you can write this with this it will show all queries of creating table and operations
jwt.secret=cGFyYWxsZWxzdGlsbGxlZnRkcml2ZW5lYWNoZ2VuZXJhbGx5dW5oYXBweWhlbHBza2luc2VsbHRvZGF5cG9wdQ==
jwt.expiration=172800000
logging.level.org.springframework.security=debug;
logging.level.org.url.shortner=debug;
frontend.url=http://localhost:5173